#!/bin/bash

declare dc
dc=$(which docker-compose)

if [[ -x "$dc" ]]; then
    :
else
    echo "Please install Docker before run this command."
    exit 2
fi

rm="--rm"

echoing() {
    echo "========================================================"
    echo "$1"
    echo "========================================================"
}

echoing "Exec Bundle Install for executing rails new command"
$dc run $rm web bundle install

echoing "Exec rails new with postgresql and webpack"
$dc run $rm web bundle exec rails new . -f -M -C -S -T --skip-spring --skip-turbolinks --skip-coffee --webpack -d=postgresql

echoing "Update config/database.yml"
mv database.default.yml config/database.yml
rm database.default.yml

echoing "Exec db create"
$dc run $rm web bundle exec rails db:create

echoing "docker-compose up"
$dc up -d

echo "You can access to localhost:3000"
